### ISSUE TITLE
3D points as input?

### ISSUE THREAD

**Issue by GrigorySamokhin** [Juzezhang/IKOL#3]
Hello! Thank's for your job!
I'm wondering if this solution can help to get smpl parameters from given 3d points of SMPL skeleton? If so, can you please provide function name in your code to solve such task

**Comment by Juzezhang** [comment]
Hello @GrigorySamokhin! Certainly, we can obtain SMPL parameters through the function smpl.IKOL(), where pred_xyz_jts_24, pred_shape, pred_phi, and pred_leaf are passed as arguments. It's advised to provide values for the twist angle and leaf angle. In case these values are not available, they can be set to zeros.

**Comment by GrigorySamokhin** [comment]
It works. Thanks a lot!
